# Generated by Django 6.0.2 on 2026-02-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document_in_passport',
            field=models.CharField(max_length=24, verbose_name='Документ пасспорта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=12, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=24, verbose_name='Призвіще'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nn_in_passport',
            field=models.CharField(max_length=24, verbose_name='nn пасспорта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(max_length=36, verbose_name='По батькові'),
        ),
    ]
