# Generated by Django 6.0.2 on 2026-03-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_shop_alter_user_photo_user_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
