# Generated by Django 6.0.2 on 2026-04-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_shop_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='poster',
            field=models.ImageField(null=True, upload_to='albums/posters/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Назва'),
        ),
    ]
