# Generated by Django 6.0.2 on 2026-04-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_shop_description_alter_shop_poster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='poster',
            field=models.ImageField(null=True, upload_to='shops/', verbose_name='Фото'),
        ),
    ]
